export const ITEM_CURRENT_PAGE = `/ITEM_CURRENT_PAGE`
export const ITEM_CURRENT_PAGE_ID = `/ITEM_CURRENT_PAGE_ID`

export const ITEM_CURRENT_LAYER = `/ITEM_CURRENT_LAYER`
export const ITEM_CURRENT_LAYER_ID = `/ITEM_CURRENT_LAYER_ID`

export const ITEM_CURRENT_IMAGE = `/ITEM_CURRENT_IMAGE`
export const ITEM_CURRENT_IMAGE_ID = `/ITEM_CURRENT_IMAGE_ID`


export const GETTER_ITEM_CURRENT_PAGE = `*${ITEM_CURRENT_PAGE}`
export const GETTER_ITEM_CURRENT_PAGE_ID = `*${ITEM_CURRENT_PAGE_ID}`
export const GETTER_ITEM_CURRENT_LAYER = `*${ITEM_CURRENT_LAYER}`
export const GETTER_ITEM_CURRENT_LAYER_ID = `*${ITEM_CURRENT_LAYER_ID}`
export const GETTER_ITEM_CURRENT_IMAGE = `*${ITEM_CURRENT_IMAGE}`
export const GETTER_ITEM_CURRENT_IMAGE_ID = `*${ITEM_CURRENT_IMAGE_ID}`