export const CHANGE_EDITOR = `CHANGE_EDITOR`
export const CHANGE_SELECTION = `CHANGE_SELECTION`
export const CHANGE_PAGE = `CHANGE_PAGE`
export const CHANGE_PAGE_NAME = `CHANGE_PAGE_NAME`
export const CHANGE_PAGE_SIZE = `CHANGE_PAGE_SIZE`

export const CHANGE_LAYER = `CHANGE_LAYER`
export const CHANGE_LAYER_NAME = 'CHANGE_LAYER_NAME'
export const CHANGE_LAYER_CLASS_NAME = 'CHANGE_LAYER_CLASS_NAME'
export const CHANGE_LAYER_ID = 'CHANGE_LAYER_ID'
export const CHANGE_LAYER_FILTER = `CHANGE_LAYER_FILTER`
export const CHANGE_LAYER_SIZE = 'CHANGE_LAYER_SIZE'
export const CHANGE_LAYER_POSITION = 'CHANGE_LAYER_POSITION'
export const CHANGE_LAYER_TRANSFORM = 'CHANGE_LAYER_TRANSFORM'
export const CHANGE_LAYER_TRANSFORM_3D = 'CHANGE_LAYER_TRANSFORM_3D'
export const CHANGE_LAYER_RADIUS = 'CHANGE_LAYER_RADIUS'
export const CHANGE_LAYER_BACKGROUND_COLOR = `CHANGE_LAYER_BACKGROUND_COLOR`
export const CHANGE_LAYER_CLIPPATH = `CHANGE_LAYER_CLIPPATH`

export const CHANGE_IMAGE = `CHANGE_IMAGE`
export const CHANGE_IMAGE_COLOR = `CHANGE_IMAGE_COLOR`
export const CHANGE_IMAGE_ANGLE = `CHANGE_IMAGE_ANGLE`
export const CHANGE_IMAGE_RADIAL_POSITION = `CHANGE_IMAGE_RADIAL_POSITION`
export const CHANGE_IMAGE_RADIAL_TYPE = `CHANGE_IMAGE_RADIAL_TYPE`
export const CHANGE_IMAGE_LINEAR_ANGLE = `CHANGE_IMAGE_LINEAR_ANGLE`

export const CHANGE_COLOR_STEP = `CHANGE_COLOR_STEP`
export const ADD_COLOR_STEP = `ADD_COLOR_STEP`
export const REMOVE_COLOR_STEP = `REMOVE_COLOR_STEP`

export const EVENT_CHANGE_EDITOR = `@${CHANGE_EDITOR}`
export const EVENT_CHANGE_SELECTION = `@${CHANGE_SELECTION}`
export const EVENT_CHANGE_PAGE = `@${CHANGE_PAGE}`
export const EVENT_CHANGE_PAGE_NAME = `@${CHANGE_PAGE_NAME}`
export const EVENT_CHANGE_PAGE_SIZE = `@${CHANGE_PAGE_SIZE}`

export const EVENT_CHANGE_LAYER = `@${CHANGE_LAYER}`
export const EVENT_CHANGE_LAYER_NAME = `@${CHANGE_LAYER_NAME}`
export const EVENT_CHANGE_LAYER_CLASS_NAME = `@${CHANGE_LAYER_CLASS_NAME}`
export const EVENT_CHANGE_LAYER_ID = `@${CHANGE_LAYER_ID}`
export const EVENT_CHANGE_LAYER_FILTER = `@${CHANGE_LAYER_FILTER}`
export const EVENT_CHANGE_LAYER_SIZE = `@${CHANGE_LAYER_SIZE}`
export const EVENT_CHANGE_LAYER_POSITION = `@${CHANGE_LAYER_POSITION}`
export const EVENT_CHANGE_LAYER_TRANSFORM = `@${CHANGE_LAYER_TRANSFORM}`
export const EVENT_CHANGE_LAYER_TRANSFORM_3D = `@${CHANGE_LAYER_TRANSFORM_3D}`
export const EVENT_CHANGE_LAYER_RADIUS = `@${CHANGE_LAYER_RADIUS}`
export const EVENT_CHANGE_LAYER_BACKGROUND_COLOR = `@${CHANGE_LAYER_BACKGROUND_COLOR}`
export const EVENT_CHANGE_LAYER_CLIPPATH = `@${CHANGE_LAYER_CLIPPATH}`

export const EVENT_CHANGE_IMAGE = `@${CHANGE_IMAGE}`
export const EVENT_CHANGE_IMAGE_COLOR = `@${CHANGE_IMAGE_COLOR}`
export const EVENT_CHANGE_IMAGE_ANGLE = `@${CHANGE_IMAGE_ANGLE}`
export const EVENT_CHANGE_IMAGE_RADIAL_POSITION = `@${CHANGE_IMAGE_RADIAL_POSITION}`
export const EVENT_CHANGE_IMAGE_RADIAL_TYPE = `@${CHANGE_IMAGE_RADIAL_TYPE}`
export const EVENT_CHANGE_IMAGE_LINEAR_ANGLE = `@${CHANGE_IMAGE_LINEAR_ANGLE}`


export const EVENT_CHANGE_COLOR_STEP = `@${CHANGE_COLOR_STEP}`
export const EVENT_ADD_COLOR_STEP = `@${ADD_COLOR_STEP}`
export const EVENT_REMOVE_COLOR_STEP = `@${REMOVE_COLOR_STEP}`