export const HISTORY_INITIALIZE = 'history/initialize'
export const HISTORY_PUSH = 'history/push'
export const HISTORY_UNDO = 'history/undo'
export const HISTORY_REDO = 'history/redo'
export const HISTORY_LIST = 'history/list'
export const HISTORY_SELECTED_CHECK = 'history/selected/check'